static/admin/config.yml

collections fix

---

static/admin/config.yml

speaker collection fix

---

src/pages/index-page.md
static/admin/config.yml

add template key for index page

---

static/admin/config.yml

cms config indentation fix

---

gatsby-node.js
package.json
src/cms/cms.js
src/cms/preview-templates/PrivacyPolicyPagePreview.js
src/components/Footer.js
src/components/NavLogo.js
src/templates/privacy-policy-page.js
yarn.lock

add privacy policy page and preview

---

src/components/Footer.js

footer fixes

---

src/cms/cms.js
src/components/PreviewCompatibleImage.js

register preview page

---

src/components/Footer.js
src/components/IndexPage/GnosisSection.js
src/components/IndexPage/SpeakersSection.js
src/components/IndexPage/StatsSection.js
src/components/NavLogo.js
src/components/Navbar.js
src/components/SpeakersPage/Speakers.js
src/templates/imprint-page.js
src/templates/privacy-policy-page.js

bg color fixes

---

src/components/IndexPage/StatsSection.js
src/components/MobileHeader.js

mobile menu

---

src/components/DesktopNav.js
src/components/Layout.js
src/components/NavLogo.js
src/components/Navbar.js
src/components/Svg/Ticket.js

change navlogo on scroll, add desktopnav container

---

src/components/Invaders.js

remove console.log

---

package.json
src/components/DesktopNav.js
src/components/IndexPage/PhotoSection.js
src/components/Layout.js
src/components/Navbar.js
yarn.lock

fix navbar animations, add buy tickets link to desktop navbar

---

src/components/Footer.js

fix footer on md screen

---

package-lock.json
package.json
src/components/Footer.js
src/components/IndexPage/GnosisSection.js
src/components/IndexPage/MainSection.js

footer fixes, change location

---

src/components/IndexPage/MainSection.js
src/components/IndexPage/StatsSection.js
static/admin/config.yml

change cms config

---

package-lock.json
src/components/Button.js
src/components/IndexPage/GnosisSection.js
src/components/IndexPage/MainSection.js
src/components/IndexPage/StatsSection.js
src/markdownRenderers.js
src/templates/index-page.js

add react-markdown, change button styles

---

src/components/Footer.js

footer fix

---

src/components/IndexPage/MainSection.js

mobile fix

---

src/components/Invaders.js
src/components/Navbar.js

fix navbar overlapping footer link

---

src/cms/cms.js
src/cms/preview-templates/CookiePolicyPagePreview.js
src/components/Footer.js
src/pages/cookie-policy.md
src/templates/cookie-policy-page.js
static/admin/config.yml

add cookie policy page

---

src/components/Invaders.js

invaders position fix

---

src/pages/cookie-policy.md

cookie policy fix

---

static/admin/config.yml

company as md

---

src/components/Speaker.js

display company as md

---

src/components/Layout.js

remove invaders on legal pages

---

src/components/Speaker.js

remove break between position and company

---

src/components/CookieBanner/styled.js
src/components/Speaker.js
yarn.lock

speaker name spacing fix, change outline color

---

src/components/DesktopNav.js

fix navbar colors for scrolled reload

---

static/admin/config.yml

sponsors cms config

---

static/admin/config.yml

cms config fix for sponsors

---

src/components/CookieBanner/CookieBanner.js

Fix cookie expiration

---

package.json
src/components/IndexPage/SponsorsSection.js
yarn.lock

Increase sponsor logo size on mobile

---

src/components/IndexPage/SponsorsSection.js

fix sponsors section

---

src/components/ButtonLink.js
src/components/IndexPage/SponsorsSection.js
src/components/Layout.js

enable invaders & open tickets buy page in a new tab

---

src/components/CookieBanner/CookieBanner.js

pre-check analytics

---

src/components/CookieBanner/CookieBanner.js
src/components/IndexPage/MainSection.js
src/components/Layout.js
src/components/SpeakersPage/Speakers.js
src/pages/speakers.js
static/admin/config.yml

fix speaker apply link, update cms config

---

src/components/Layout.js

update og metas

---

src/components/Layout.js

add twitter tags

---

package.json
src/components/DesktopNav.js
yarn.lock

update dependencies, fix desktop navigation

---

src/components/Footer.js
src/components/IndexPage/SponsorsSection.js
src/pages/sponsors/become-a-sponsor-become-a-sponsor.md

fix sponsor links

---

package.json
src/components/Layout.js
yarn.lock

an attempt to fix cms page preview

---

src/cms/preview-templates/IndexPagePreview.js

fix landing page preview

---

src/components/ButtonLink.js

fix buttonLink rel

---

src/pages/index-page.md

fix speaker on landing page

---

src/components/Speaker.js

add transition to glasses img

---

src/pages/podcasts.md

fix build error

---

src/templates/podcasts-page.js

add podcasts page js file

---

static/admin/config.yml

update speaker model

---

src/components/PodcastLink.js
src/components/Speaker.js
src/templates/podcast-page.js

fix podcast page, add border-radius to podcast button and speaker photos

---

src/components/Speaker.js

fix podcast bubble

---

package.json
src/cms/preview-templates/IndexPagePreview.js
src/components/IndexPage/DappsSection.js
src/components/IndexPage/StatsSection.js
src/pages/index-page.md
src/templates/index-page.js
static/admin/config.yml
yarn.lock

Website 2020

---

src/pages/tickets.md
src/templates/tickets-page.js
static/admin/config.yml

tickets page fix

---

src/components/DesktopNav.js
src/components/IndexPage/MainSection.js
static/admin/config.yml

fix 2019 speakers folder

---

src/components/TicketsPage/BuySection/BuyButton.js
src/components/TicketsPage/BuySection/index.js
src/components/TicketsPage/MainSection.js

fix tickets page

---

src/components/Layout.js
src/components/TicketsPage/BuySection/BuyButton.js

mintbase integration

---

src/components/Layout.js

fix og image

---

src/components/DappsPage/Dapp.js
src/components/DesktopNav.js
src/components/IndexPage/DappsSection.js
src/components/IndexPage/MainSection.js
src/pages/dapps.js
static/admin/config.yml

dapps page wip, cms config update

---

src/components/DappsPage/Dapp.js
src/pages/dapps/gnosis-safe-multisig-gnosis-safe-multisig.md
src/pages/dapps/mintbase-mintbase.md
src/pages/dapps/poap-poap.md
src/pages/dapps/trustlines-trustlines.md

add empty lines

---

src/components/DappsPage/Dapp.js
src/components/ShowOnMobile.js
src/pages/dapps.js

Website 2020 updates round 1

---

src/components/IndexPage/MainSection.js
src/components/MobileHeader.js

fix mobile dapps page link

---

package.json
src/components/ButtonLink.js
src/components/DappsPage/Dapp.js
yarn.lock

fix hovers on dapps page

---

src/components/DappsPage/Dapp.js
src/components/IndexPage/DappsSection.js
src/pages/dapps.js

Expand dapp when clicking from carousel

---

src/pages/dapps.js

fix .dappUrl access

---

src/components/IndexPage/Video2019.js

hover effect for btn

---

src/components/IndexPage/Edition2019Section.js
src/components/IndexPage/Video2019.js
src/components/MobileHeader.js
src/components/Navbar.js

feedback fixes

---

src/components/IndexPage/StatsSection.js
src/components/MobileHeader.js

feedback fixes [2]

---

src/components/IndexPage/Edition2019Section.js
src/components/Speaker.js
src/components/Svg/DappconIllus.js

feedback fixes [3]

---

.travis.yml

This is a requirement to allow to upload to different S3 bucket regions

Add region to travis S3 deployment
